# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LicenseGenerator < Formula
  desc "Create licenses easily from your terminal"
  homepage "https://github.com/Jimvid/license-generator"
  version "0.1"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jimvid/license-generator/releases/download/v0.1/license-generator_Darwin_x86_64.tar.gz"
      sha256 "ce0c5e6533b0abb5363be4a9469ee2b10bcbf2e640e609a97ef2cb00aec3a4fc"

      def install
        bin.install "license-generator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Jimvid/license-generator/releases/download/v0.1/license-generator_Darwin_arm64.tar.gz"
      sha256 "e26b647f17c726c159cded4d28f264140bd78615ae943cfb6bdef973acfb6073"

      def install
        bin.install "license-generator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jimvid/license-generator/releases/download/v0.1/license-generator_Linux_arm64.tar.gz"
      sha256 "026d45cc386d781d744226307a59f5a647deee4bbf23520b40064d54ada21e7c"

      def install
        bin.install "license-generator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Jimvid/license-generator/releases/download/v0.1/license-generator_Linux_x86_64.tar.gz"
      sha256 "2df609252e5e8156f7623e1c59667c251f3952894fe479e62c4dbbbba5c7962b"

      def install
        bin.install "license-generator"
      end
    end
  end
end
